name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Streamlit App
        run: curl -s https://hellas-grid-monitor-8crhzwsrk3526nxeuoxdni.streamlit.app/ > /dev/null
